version: '3'
services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  # kafka:
  #   container_name: kafka
  #   image: spotify/kafka:latest
  #   ports:
  #    - 2181:2181
  #    - 9092:9092
  #   networks:
  #     - my-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - my-network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - my-network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"


  ts-ui-dashboard:
    container_name: ts-ui-dashboard
    image: ts/ts-ui-dashboard
    restart: always
    ports:
      - 80:8080
    networks:
      - my-network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  ts-login-service:
    image: ts/ts-login-service
    restart: always
    ports:
      - 12342:12342
    networks:
      - my-network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  ts-account-mongo:
    image: mongo
    networks:
      - my-network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  ts-route-service:
    image: ts/ts-route-service
    restart: always
    ports:
         - 11178:11178
    networks:
      - my-network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  ts-route-mongo:
    image: mongo
    networks:
        - my-network
        



  ts-register-service:
    image: ts/ts-register-service
    restart: always
    ports:
      - 12344:12344
    networks:
      - my-network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"


  ts-sso-service:
    image: ts/ts-sso-service
    restart: always
    ports:
      - 12349:12349
    networks:
      - my-network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"


networks:
    my-network:
    
      # driver: overlay
      
      driver: bridge




